# Generated by Django 3.0.7 on 2020-07-11 15:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jezyk', models.CharField(choices=[('JS', 'Java Script'), ('Py', 'Python'), ('HTML', 'html'), ('C', 'c'), ('C++', 'c++'), ('C#', 'c#'), ('Java', 'java'), ('PHP', 'php'), ('RUBY', 'Ruby'), ('Julia', 'julia'), ('Go', 'go'), ('R', 'r')], max_length=15)),
                ('biblioteka', models.CharField(max_length=30)),
                ('rodzaj', multiselectfield.db.fields.MultiSelectField(max_length=200, verbose_name=[('Interpreted', 'Interpreted'), ('Functional', 'Functional'), ('Compiled', 'Compiled'), ('Procedural', 'Procedural'), ('Scripting', 'Scripting'), ('Markup', 'Markup'), ('Logic-Based', 'Logic-Based'), ('Concurrent', 'Concurrent'), ('Object-Oriented', 'Object-Oriented')])),
                ('opis', models.CharField(max_length=300)),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
