# Generated by Django 3.0.7 on 2020-07-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologie',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
